---
- name: Creating test environment
- hosts: all
  remote_user: loopec
  become: yes

  tasks:
    - name: "Install pip3"
      apt:
          name: python3-pip

    - name: "Touch file"
      file:
        path: /home/loopec/test.txt
        state: touch
