name: Ansible Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Ansible code verification
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Ansible
        run: sudo apt install ansible

      - name: Run code test
        run: |
          cd ansible
          for item in *; do cd $item && ansible-playbook $item --syntax-check; done

      