name: Ansible Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Ansible code verification
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install Ansible
        run: sudo apt install ansible

      # Runs a set of commands using the runners shell
      - name: Run code test
        run: ansible-playbook ansible_environment.yml --syntax-check
